# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Kyle LeNeau
tagline: A site made of bytes
description: 'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: http://kyleleneau.com
baseurl: /

author:
  name: 'Kyle LeNeau'
  url: https://twitter.com/kleneau

paginate: 5

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/kyleleneau/kyleleneau.com

# Google Analytics
google_analytics_tracking_id: UA-4755411-11

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

gems:
  - jekyll-redirect-from
  - jekyll-sitemap