#
# Blog Settings
#
author: Kyle LeNeau
description: A site made of bytes
url: http://kyleleneau.com
baseurl: 
title: Kyle LeNeau
subtitle: A site made of bytes
gravatar_url: http://www.gravatar.com/avatar/f86ee0129fd77b9a468f0aedb00cc4dd.png
subscribe_rss: 

# Github repositories
github_user: KyleLeneau
github_repo_url: https://github.com/KyleLeneau/kyleleneau.com/

# Twitter
twitter_user: kleneau
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: kleneau
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-4755411-11


#
# Jekyll Settings
#
markdown: redcarpet
highlighter: pygments
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap